checking is github access to sonarqube

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,10 +2,19 @@ name: Auto comment on Push and Pull Request
 
 on: 
   pull_request:
-    branches: []
+    branches: 
+      - main
+      - dev
 
 
 jobs:
+
+  test_sonarqube_connection:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check HTTP access to sonarqube 
+        run: |
+          curl -v http://54.158.35.213:9000 || echo "connection failed"
 
   comment_on_pr:
     if: github.event_name == 'pull_request'
@@ -19,7 +28,10 @@ jobs:
           SONAR_TOKEN: sqa_acf14b025b0a8a8b841cf761b5267f9fc32fe544
           SONAR_HOST_URL: http://34.203.199.42:9000
         with:
-          args: -Dsonar.projectKey=scrapping_poc
+          projectBaseDir:
+          extraProperties: |
+
+          # args: -Dsonar.projectKey=scrapping_poc
       - name: Comment on pull request
         run: |
           PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
